import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeModeScript } from "flowbite-react";
import NavbarMain from "@/components/navbar/NavbarMain";
import { SidebarLeft } from "@/components/sidebarLeft/SidebarLeft";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ThemeModeScript />
      </head>
      <body
        className={
          inter.className + " dark:bg-gray-800 bg-white dark:text-white"
        }
      >
        <NavbarMain />
        <div className="flex container mx-auto">
          <div className="border-r border-gray-100 dark:border-gray-700 h-[calc(100vh-57px)] sticky top-[57px]">
            <SidebarLeft />
          </div>
          <div className="flex-1 relative">{children}</div>
        </div>
      </body>
    </html>
  );
}
